-- BizBox Initial Data Seed

USE direco_com;

-- Insert Products
INSERT INTO products (name_ru, name_uk, name_en, name_es, description_ru, description_uk, description_en, description_es, niche, price_usd, average_monthly_income, roi_percentage, setup_time_days, image_url, status) VALUES
('Салон инъекционной косметики', 'Салон інʼєкційної косметики', 'Injectable Cosmetics Salon', 'Salón de Cosmetología Inyectable', 'Готовый бизнес по продаже инъекционных процедур с полной клиентской базой и оборудованием', 'Готовий бізнес з продажу ін''єкційних процедур з повною базою клієнтів', 'Complete injectable cosmetics salon business with client base and equipment', 'Negocio completo de salón de cosmetología inyectable con base de clientes', 'cosmetics', 50000, 250000, 380, 7, 'https://via.placeholder.com/300?text=Cosmetics', 'active'),
('Медицинская клиника', 'Медична клініка', 'Medical Clinic', 'Clínica Médica Completa', 'Готовая структура для открытия своей клиники с документами и процессами', 'Готова структура для відкриття своєї клініки з документами та процесами', 'Complete medical clinic structure with documents and processes', 'Estructura completa de clínica médica con documentos y procesos', 'healthcare', 120999, 450000, 420, 14, 'https://via.placeholder.com/300?text=Healthcare', 'active'),
('Финансовый сервис', 'Фінансовий сервіс', 'Financial Services Platform', 'Plataforma de Servicios Financieros', 'Готовая платформа для финансовых услуг и инвестиций', 'Готова платформа для фінансових послуг та інвестицій', 'Complete financial services and investment platform', 'Plataforma completa de servicios financieros e inversiones', 'fintech', 330000, 850000, 520, 21, 'https://via.placeholder.com/300?text=Fintech', 'active');

-- Insert Cases/Testimonials
INSERT INTO cases (title_ru, title_uk, title_en, title_es, client_name, niche, initial_investment, revenue_month_6, profit_monthly, roi_percentage, testimonial_ru, testimonial_uk, testimonial_en, testimonial_es, rating, featured) VALUES
('Кейс: Салон косметики Влады', 'Кейс: Салон косметики Влади', 'Case: Vlada Beauty Salon', 'Caso: Salón de Belleza de Vlada', 'Влада С., Москва', 'cosmetics', 50000, 280000, 140000, 380, 'За 7 дней запустили салон с нуля, выручка 280k в месяц за 6 месяцев. Отличная поддержка на всех этапах!', 'За 7 днів запустили салон з нуля, виручка 280k на місяць за 6 місяців. Відмінна підтримка на всіх етапах!', 'Launched salon from scratch in 7 days, achieving $280k monthly revenue in 6 months. Excellent support throughout!', 'Salón lanzado desde cero en 7 días, logrando $280k de ingresos mensuales en 6 meses. ¡Excelente apoyo en todo!', 5, TRUE),
('Кейс: Клиника доктора Петрова', 'Кейс: Клініка лікаря Петрова', 'Case: Dr Petrov Clinic', 'Caso: Clínica del Dr. Petrov', 'Петр П., СПб', 'healthcare', 120999, 450000, 225000, 420, 'Документы за 2 недели, пациенты с первого дня. Прибыль растет каждый месяц на 15-20%.', 'Документи за 2 тижні, пацієнти з першого дня. Прибуток зростає кожного місяця на 15-20%.', 'Documents in 2 weeks, patients from day one. Profit growing 15-20% monthly.', 'Documentos en 2 semanas, pacientes desde el primer día. Ganancias creciendo 15-20% mensualmente.', 5, TRUE),
('Кейс: FinTech стартап Игоря', 'Кейс: FinTech стартап Ігоря', 'Case: Igor FinTech Startup', 'Caso: Startup FinTech de Igor', 'Игорь Т., Киев', 'fintech', 330000, 850000, 425000, 520, 'Платформа за 3 недели, 5000+ клиентов привлекли в первый месяц. Лучшее решение!', 'Платформа за 3 тижні, 5000+ клієнтів залучили в перший місяць. Найкраще рішення!', 'Platform in 3 weeks, attracted 5000+ customers in first month. Best solution ever!', 'Plataforma en 3 semanas, atrajo 5000+ clientes en el primer mes. ¡La mejor solución!', 5, TRUE);
